### ISSUE TITLE
Looks this tool doesn't work as expected

### ISSUE THREAD

**Issue by kesihai** [yangziwen/diff-checkstyle#2]
Hi yangziwen,
I also meet the issue that this repo want to solve. I want to checkstyle to check the changed code , and not the whole file. looks this jar doesn't work as expected, do you still maintain this repo ? how do you deal with this issue now ?

**Comment by yangziwen** [comment]
Would you like to tell me how you used this tool (run the command directly or invoked through the git hook ) and what is the difference between the output and your expection?

Generally speaking, this tool will only check the changed files between  the base-rev (an old commit in the history) and your latest commit (the HEAD) on your current branch, then output the style problems related to the modified codes between the two commits. 

Please show me more details about the problem you met, and be aware that this tool can only work with Git but not any other version control system.

**Comment by kesihai** [comment]
Sorry, I didn't use this tool in the right way, fantistic tool .
