### ISSUE TITLE
jenkins上使用

### ISSUE THREAD

**Issue by yang378848032** [yangziwen/diff-checkstyle#6]
这个插件不能作为单独的插件来使用吗？在jenkins上生成html报告

**Comment by yangziwen** [comment]
diff-checkstyle.jar本质上是一个命令行工具，如果追加`-f xml -o ${filepath}`的参数，是可以生成xml格式的报告文件的。

checkstyle跟jenkins的整合，原理上是基于checkstyle生成的xml文件，进一步生成html报告的。

所以可以参考下[https://blog.csdn.net/gongxsh00/article/details/81172203](https://blog.csdn.net/gongxsh00/article/details/81172203)，把diff-checkstyle.jar上传到jenkins_home目录里，然后替换下command中设置的命令试试。

不过我估计成功的可能性比较小，因为目前diff-checkstyle工具依赖的并不是最新版本的checkstyle，产出的xml报告跟jenkins的checkstyle插件有可能不兼容。

**Comment by yang378848032** [comment]
好的，谢谢
